const INST_DEC = {
    DEC: 'DECLARACION',
    DEC_VECTOR_T1_D1: 'DECLARACION_VECTOR_T1_D1',
    DEC_VECTOR_T1_D2: 'DECLARACION_VECTOR_T1_D2',
    DEC_VECTOR_T2_D1: 'DECLARACION_VECTOR_T2_D1',
    DEC_VECTOR_T2_D2: 'DECLARACION_VECTOR_T2_D2',
    DEC_METODO: 'DECLARACION_METODO'
}

const INST_ASIG = {
    CASTEO: 'CASTEO',
    INCREMENTO: 'INCREMENTO',
    DECREMENTO: 'DECREMENTO',
    ASIGNACION: 'ASIGNACION',
    MOD_VECTOR_D1: 'MODIFICACION_VECTOR_D1',
    MOD_VECTOR_D2: 'MODIFICACION_VECTOR_D2',
    CALL_METODO: 'CALL_METODO'
}

const INST_CONTROL = {
    IF: 'IF',
    ELIF: 'ELIF',
    ELSE: 'ELSE',
    SWITCH: 'SWTICH',
    CASE: 'CASE_NORMAL',
    DEFAULT: 'CASE_DEFAULT'
}

const INST_TRANSFERENCIA = {
    BREAK: 'BREAK',
    CONTINUE: 'CONTINUE',
    RETURN: 'RETURN'
}

const INST_CICLOS = {
    WHILE: 'WHILE',
    FOR: 'FOR',
    DO_WHILE: 'DO_WHILE',
    DO_UNTIL: 'DO_UNTIL'
}

const INST_NATIVA = {
    PRINT: 'PRINT',
    PRINTLN: 'PRINTLN',
    ROUND: 'ROUND',
    LENGTH: 'LENGTH',
    TYPEOF: 'TYPEOF',
    TOSTRING: 'TOSTRING',
    TOCHARARRAY: 'TOCHARARRAY',
    TOLOWER: 'TOLOWER',
    TOUPPER: 'TOUPPER',
    RUN: 'RUN',
    PUSH: 'PUSH',
    POP: 'POP'
}

module.exports = {
    INST_DEC,
    INST_ASIG,
    INST_CONTROL,
    INST_CICLOS,
    INST_TRANSFERENCIA,
    INST_NATIVA
}

